//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 08:40:06 AM CEST 
//


package domain.v2.drazba;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nazov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cislo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ZoDna" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Drazobnik" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
 *         &lt;element name="Navrhovatelia">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Navrhovatel" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Licitatori">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Licitator" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Notar" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}CeleMeno"/>
 *                   &lt;element name="Sidlo" type="{/PortalJustice/XmlFormularObchodnyVestnik/}Sidlo"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="KonanieMiesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KonanieDatum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="KonanieCas" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Kolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Predmet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetOpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetStavOpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetPravaZavazky" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetCenaOdhad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetCenaVyska" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetCenaSposobStanovenia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PredmetPodmienkyOdovzdania" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NajnizsiePodanie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NajvyssiePodanie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinimalnePrihodenie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Zabezpeka">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Vyska" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ZlozenieSposob" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ZlozenieCisloUctu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ZlozenieAdresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ZlozenieDoklad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ZlozenieLehota" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Vratenie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SposobUhradyCeny" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObhliadkaDatum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObhliadkaMiesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpolocnaDrazba" type="{/PortalJustice/XmlFormularObchodnyVestnik/}XmlDropDownValue"/>
 *         &lt;element name="SpolocnaDrazbaPoradieDrazeniePredmetov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrganizaceOpatrenia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NadobudnutieVlastnickehoPrava" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DovodUpustenia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DrazobnikOznamuje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazov",
    "cislo",
    "zoDna",
    "drazobnik",
    "navrhovatelia",
    "licitatori",
    "notar",
    "konanieMiesto",
    "konanieDatum",
    "konanieCas",
    "kolo",
    "predmet",
    "predmetOpis",
    "predmetStavOpis",
    "predmetPravaZavazky",
    "predmetCenaOdhad",
    "predmetCenaVyska",
    "predmetCenaSposobStanovenia",
    "predmetPodmienkyOdovzdania",
    "najnizsiePodanie",
    "najvyssiePodanie",
    "minimalnePrihodenie",
    "zabezpeka",
    "sposobUhradyCeny",
    "obhliadkaDatum",
    "obhliadkaMiesto",
    "spolocnaDrazba",
    "spolocnaDrazbaPoradieDrazeniePredmetov",
    "organizaceOpatrenia",
    "nadobudnutieVlastnickehoPrava",
    "dovodUpustenia",
    "drazobnikOznamuje"
})
@XmlRootElement(name = "Drazba")
public class Drazba {

    @XmlElement(name = "Nazov", required = true)
    protected String nazov;
    @XmlElement(name = "Cislo", required = true)
    protected String cislo;
    @XmlElement(name = "ZoDna", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar zoDna;
    @XmlElement(name = "Drazobnik", required = true)
    protected PravnickaOsoba drazobnik;
    @XmlElement(name = "Navrhovatelia", required = true, nillable = true)
    protected Drazba.Navrhovatelia navrhovatelia;
    @XmlElement(name = "Licitatori", required = true, nillable = true)
    protected Drazba.Licitatori licitatori;
    @XmlElementRef(name = "Notar", namespace = "/PortalJustice/XmlFormularObchodnyVestnik/", type = JAXBElement.class, required = false)
    protected JAXBElement<Notar> notar;
    @XmlElement(name = "KonanieMiesto", required = true)
    protected String konanieMiesto;
    @XmlElement(name = "KonanieDatum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar konanieDatum;
    @XmlElement(name = "KonanieCas", required = true)
    protected String konanieCas;
    @XmlElement(name = "Kolo", required = true)
    protected String kolo;
    @XmlElement(name = "Predmet", required = true)
    protected String predmet;
    @XmlElement(name = "PredmetOpis", required = true, nillable = true)
    protected String predmetOpis;
    @XmlElement(name = "PredmetStavOpis", required = true, nillable = true)
    protected String predmetStavOpis;
    @XmlElement(name = "PredmetPravaZavazky", required = true, nillable = true)
    protected String predmetPravaZavazky;
    @XmlElement(name = "PredmetCenaOdhad", required = true, nillable = true)
    protected String predmetCenaOdhad;
    @XmlElement(name = "PredmetCenaVyska", required = true, nillable = true)
    protected String predmetCenaVyska;
    @XmlElement(name = "PredmetCenaSposobStanovenia", required = true, nillable = true)
    protected String predmetCenaSposobStanovenia;
    @XmlElement(name = "PredmetPodmienkyOdovzdania", required = true, nillable = true)
    protected String predmetPodmienkyOdovzdania;
    @XmlElement(name = "NajnizsiePodanie", required = true, nillable = true)
    protected String najnizsiePodanie;
    @XmlElement(name = "NajvyssiePodanie", required = true, nillable = true)
    protected String najvyssiePodanie;
    @XmlElement(name = "MinimalnePrihodenie", required = true, nillable = true)
    protected String minimalnePrihodenie;
    @XmlElement(name = "Zabezpeka", required = true, nillable = true)
    protected Drazba.Zabezpeka zabezpeka;
    @XmlElement(name = "SposobUhradyCeny", required = true, nillable = true)
    protected String sposobUhradyCeny;
    @XmlElement(name = "ObhliadkaDatum", required = true, nillable = true)
    protected String obhliadkaDatum;
    @XmlElement(name = "ObhliadkaMiesto", required = true, nillable = true)
    protected String obhliadkaMiesto;
    @XmlElement(name = "SpolocnaDrazba", required = true)
    protected XmlDropDownValue spolocnaDrazba;
    @XmlElement(name = "SpolocnaDrazbaPoradieDrazeniePredmetov", required = true, nillable = true)
    protected String spolocnaDrazbaPoradieDrazeniePredmetov;
    @XmlElement(name = "OrganizaceOpatrenia", required = true, nillable = true)
    protected String organizaceOpatrenia;
    @XmlElement(name = "NadobudnutieVlastnickehoPrava", required = true, nillable = true)
    protected String nadobudnutieVlastnickehoPrava;
    @XmlElement(name = "DovodUpustenia", required = true, nillable = true)
    protected String dovodUpustenia;
    @XmlElement(name = "DrazobnikOznamuje", required = true, nillable = true)
    protected String drazobnikOznamuje;

    /**
     * Gets the value of the nazov property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNazov() {
        return nazov;
    }

    /**
     * Sets the value of the nazov property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNazov(String value) {
        this.nazov = value;
    }

    /**
     * Gets the value of the cislo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCislo() {
        return cislo;
    }

    /**
     * Sets the value of the cislo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCislo(String value) {
        this.cislo = value;
    }

    /**
     * Gets the value of the zoDna property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getZoDna() {
        return zoDna;
    }

    /**
     * Sets the value of the zoDna property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setZoDna(XMLGregorianCalendar value) {
        this.zoDna = value;
    }

    /**
     * Gets the value of the drazobnik property.
     *
     * @return
     *     possible object is
     *     {@link PravnickaOsoba }
     *
     */
    public PravnickaOsoba getDrazobnik() {
        return drazobnik;
    }

    /**
     * Sets the value of the drazobnik property.
     *
     * @param value
     *     allowed object is
     *     {@link PravnickaOsoba }
     *
     */
    public void setDrazobnik(PravnickaOsoba value) {
        this.drazobnik = value;
    }

    /**
     * Gets the value of the navrhovatelia property.
     *
     * @return
     *     possible object is
     *     {@link Drazba.Navrhovatelia }
     *
     */
    public Drazba.Navrhovatelia getNavrhovatelia() {
        return navrhovatelia;
    }

    /**
     * Sets the value of the navrhovatelia property.
     *
     * @param value
     *     allowed object is
     *     {@link Drazba.Navrhovatelia }
     *
     */
    public void setNavrhovatelia(Drazba.Navrhovatelia value) {
        this.navrhovatelia = value;
    }

    /**
     * Gets the value of the licitatori property.
     *
     * @return
     *     possible object is
     *     {@link Drazba.Licitatori }
     *
     */
    public Drazba.Licitatori getLicitatori() {
        return licitatori;
    }

    /**
     * Sets the value of the licitatori property.
     *
     * @param value
     *     allowed object is
     *     {@link Drazba.Licitatori }
     *
     */
    public void setLicitatori(Drazba.Licitatori value) {
        this.licitatori = value;
    }

    /**
     * Gets the value of the notar property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Drazba.Notar }{@code >}
     *
     */
    public JAXBElement<Notar> getNotar() {
        return notar;
    }

    /**
     * Sets the value of the notar property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Drazba.Notar }{@code >}
     *
     */
    public void setNotar(JAXBElement<Notar> value) {
        this.notar = value;
    }

    /**
     * Gets the value of the konanieMiesto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKonanieMiesto() {
        return konanieMiesto;
    }

    /**
     * Sets the value of the konanieMiesto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKonanieMiesto(String value) {
        this.konanieMiesto = value;
    }

    /**
     * Gets the value of the konanieDatum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getKonanieDatum() {
        return konanieDatum;
    }

    /**
     * Sets the value of the konanieDatum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setKonanieDatum(XMLGregorianCalendar value) {
        this.konanieDatum = value;
    }

    /**
     * Gets the value of the konanieCas property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKonanieCas() {
        return konanieCas;
    }

    /**
     * Sets the value of the konanieCas property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKonanieCas(String value) {
        this.konanieCas = value;
    }

    /**
     * Gets the value of the kolo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKolo() {
        return kolo;
    }

    /**
     * Sets the value of the kolo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKolo(String value) {
        this.kolo = value;
    }

    /**
     * Gets the value of the predmet property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmet() {
        return predmet;
    }

    /**
     * Sets the value of the predmet property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmet(String value) {
        this.predmet = value;
    }

    /**
     * Gets the value of the predmetOpis property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetOpis() {
        return predmetOpis;
    }

    /**
     * Sets the value of the predmetOpis property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetOpis(String value) {
        this.predmetOpis = value;
    }

    /**
     * Gets the value of the predmetStavOpis property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetStavOpis() {
        return predmetStavOpis;
    }

    /**
     * Sets the value of the predmetStavOpis property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetStavOpis(String value) {
        this.predmetStavOpis = value;
    }

    /**
     * Gets the value of the predmetPravaZavazky property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetPravaZavazky() {
        return predmetPravaZavazky;
    }

    /**
     * Sets the value of the predmetPravaZavazky property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetPravaZavazky(String value) {
        this.predmetPravaZavazky = value;
    }

    /**
     * Gets the value of the predmetCenaOdhad property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetCenaOdhad() {
        return predmetCenaOdhad;
    }

    /**
     * Sets the value of the predmetCenaOdhad property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetCenaOdhad(String value) {
        this.predmetCenaOdhad = value;
    }

    /**
     * Gets the value of the predmetCenaVyska property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetCenaVyska() {
        return predmetCenaVyska;
    }

    /**
     * Sets the value of the predmetCenaVyska property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetCenaVyska(String value) {
        this.predmetCenaVyska = value;
    }

    /**
     * Gets the value of the predmetCenaSposobStanovenia property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetCenaSposobStanovenia() {
        return predmetCenaSposobStanovenia;
    }

    /**
     * Sets the value of the predmetCenaSposobStanovenia property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetCenaSposobStanovenia(String value) {
        this.predmetCenaSposobStanovenia = value;
    }

    /**
     * Gets the value of the predmetPodmienkyOdovzdania property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPredmetPodmienkyOdovzdania() {
        return predmetPodmienkyOdovzdania;
    }

    /**
     * Sets the value of the predmetPodmienkyOdovzdania property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPredmetPodmienkyOdovzdania(String value) {
        this.predmetPodmienkyOdovzdania = value;
    }

    /**
     * Gets the value of the najnizsiePodanie property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNajnizsiePodanie() {
        return najnizsiePodanie;
    }

    /**
     * Sets the value of the najnizsiePodanie property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNajnizsiePodanie(String value) {
        this.najnizsiePodanie = value;
    }

    /**
     * Gets the value of the najvyssiePodanie property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNajvyssiePodanie() {
        return najvyssiePodanie;
    }

    /**
     * Sets the value of the najvyssiePodanie property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNajvyssiePodanie(String value) {
        this.najvyssiePodanie = value;
    }

    /**
     * Gets the value of the minimalnePrihodenie property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMinimalnePrihodenie() {
        return minimalnePrihodenie;
    }

    /**
     * Sets the value of the minimalnePrihodenie property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMinimalnePrihodenie(String value) {
        this.minimalnePrihodenie = value;
    }

    /**
     * Gets the value of the zabezpeka property.
     *
     * @return
     *     possible object is
     *     {@link Drazba.Zabezpeka }
     *
     */
    public Drazba.Zabezpeka getZabezpeka() {
        return zabezpeka;
    }

    /**
     * Sets the value of the zabezpeka property.
     *
     * @param value
     *     allowed object is
     *     {@link Drazba.Zabezpeka }
     *
     */
    public void setZabezpeka(Drazba.Zabezpeka value) {
        this.zabezpeka = value;
    }

    /**
     * Gets the value of the sposobUhradyCeny property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSposobUhradyCeny() {
        return sposobUhradyCeny;
    }

    /**
     * Sets the value of the sposobUhradyCeny property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSposobUhradyCeny(String value) {
        this.sposobUhradyCeny = value;
    }

    /**
     * Gets the value of the obhliadkaDatum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObhliadkaDatum() {
        return obhliadkaDatum;
    }

    /**
     * Sets the value of the obhliadkaDatum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObhliadkaDatum(String value) {
        this.obhliadkaDatum = value;
    }

    /**
     * Gets the value of the obhliadkaMiesto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObhliadkaMiesto() {
        return obhliadkaMiesto;
    }

    /**
     * Sets the value of the obhliadkaMiesto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObhliadkaMiesto(String value) {
        this.obhliadkaMiesto = value;
    }

    /**
     * Gets the value of the spolocnaDrazba property.
     *
     * @return
     *     possible object is
     *     {@link XmlDropDownValue }
     *
     */
    public XmlDropDownValue getSpolocnaDrazba() {
        return spolocnaDrazba;
    }

    /**
     * Sets the value of the spolocnaDrazba property.
     *
     * @param value
     *     allowed object is
     *     {@link XmlDropDownValue }
     *
     */
    public void setSpolocnaDrazba(XmlDropDownValue value) {
        this.spolocnaDrazba = value;
    }

    /**
     * Gets the value of the spolocnaDrazbaPoradieDrazeniePredmetov property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSpolocnaDrazbaPoradieDrazeniePredmetov() {
        return spolocnaDrazbaPoradieDrazeniePredmetov;
    }

    /**
     * Sets the value of the spolocnaDrazbaPoradieDrazeniePredmetov property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSpolocnaDrazbaPoradieDrazeniePredmetov(String value) {
        this.spolocnaDrazbaPoradieDrazeniePredmetov = value;
    }

    /**
     * Gets the value of the organizaceOpatrenia property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrganizaceOpatrenia() {
        return organizaceOpatrenia;
    }

    /**
     * Sets the value of the organizaceOpatrenia property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrganizaceOpatrenia(String value) {
        this.organizaceOpatrenia = value;
    }

    /**
     * Gets the value of the nadobudnutieVlastnickehoPrava property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNadobudnutieVlastnickehoPrava() {
        return nadobudnutieVlastnickehoPrava;
    }

    /**
     * Sets the value of the nadobudnutieVlastnickehoPrava property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNadobudnutieVlastnickehoPrava(String value) {
        this.nadobudnutieVlastnickehoPrava = value;
    }

    /**
     * Gets the value of the dovodUpustenia property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDovodUpustenia() {
        return dovodUpustenia;
    }

    /**
     * Sets the value of the dovodUpustenia property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDovodUpustenia(String value) {
        this.dovodUpustenia = value;
    }

    /**
     * Gets the value of the drazobnikOznamuje property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDrazobnikOznamuje() {
        return drazobnikOznamuje;
    }

    /**
     * Sets the value of the drazobnikOznamuje property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDrazobnikOznamuje(String value) {
        this.drazobnikOznamuje = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Licitator" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "licitator"
    })
    public static class Licitatori {

        @XmlElement(name = "Licitator", required = true)
        protected List<Licitator> licitator;

        /**
         * Gets the value of the licitator property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the licitator property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLicitator().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Drazba.Licitatori.Licitator }
         *
         *
         */
        public List<Licitator> getLicitator() {
            if (licitator == null) {
                licitator = new ArrayList<Licitator>();
            }
            return this.licitator;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "celeMeno"
        })
        public static class Licitator {

            @XmlElement(name = "Id")
            protected int id;
            @XmlElement(name = "CeleMeno", required = true)
            protected PravnickaOsoba celeMeno;

            /**
             * Gets the value of the id property.
             *
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the celeMeno property.
             *
             * @return
             *     possible object is
             *     {@link PravnickaOsoba }
             *
             */
            public PravnickaOsoba getCeleMeno() {
                return celeMeno;
            }

            /**
             * Sets the value of the celeMeno property.
             *
             * @param value
             *     allowed object is
             *     {@link PravnickaOsoba }
             *
             */
            public void setCeleMeno(PravnickaOsoba value) {
                this.celeMeno = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Navrhovatel" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "navrhovatel"
    })
    public static class Navrhovatelia {

        @XmlElement(name = "Navrhovatel", required = true)
        protected List<Navrhovatel> navrhovatel;

        /**
         * Gets the value of the navrhovatel property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the navrhovatel property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNavrhovatel().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Drazba.Navrhovatelia.Navrhovatel }
         *
         *
         */
        public List<Navrhovatel> getNavrhovatel() {
            if (navrhovatel == null) {
                navrhovatel = new ArrayList<Navrhovatel>();
            }
            return this.navrhovatel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}PravnickaOsoba"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "celeMeno"
        })
        public static class Navrhovatel {

            @XmlElement(name = "Id")
            protected int id;
            @XmlElement(name = "CeleMeno", required = true)
            protected PravnickaOsoba celeMeno;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the celeMeno property.
             * 
             * @return
             *     possible object is
             *     {@link PravnickaOsoba }
             *     
             */
            public PravnickaOsoba getCeleMeno() {
                return celeMeno;
            }

            /**
             * Sets the value of the celeMeno property.
             * 
             * @param value
             *     allowed object is
             *     {@link PravnickaOsoba }
             *     
             */
            public void setCeleMeno(PravnickaOsoba value) {
                this.celeMeno = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CeleMeno" type="{/PortalJustice/XmlFormularObchodnyVestnik/}CeleMeno"/>
     *         &lt;element name="Sidlo" type="{/PortalJustice/XmlFormularObchodnyVestnik/}Sidlo"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "celeMeno",
        "sidlo"
    })
    public static class Notar {

        @XmlElement(name = "CeleMeno", required = true)
        protected CeleMeno celeMeno;
        @XmlElement(name = "Sidlo", required = true)
        protected Sidlo sidlo;

        /**
         * Gets the value of the celeMeno property.
         * 
         * @return
         *     possible object is
         *     {@link CeleMeno }
         *     
         */
        public CeleMeno getCeleMeno() {
            return celeMeno;
        }

        /**
         * Sets the value of the celeMeno property.
         * 
         * @param value
         *     allowed object is
         *     {@link CeleMeno }
         *     
         */
        public void setCeleMeno(CeleMeno value) {
            this.celeMeno = value;
        }

        /**
         * Gets the value of the sidlo property.
         * 
         * @return
         *     possible object is
         *     {@link Sidlo }
         *     
         */
        public Sidlo getSidlo() {
            return sidlo;
        }

        /**
         * Sets the value of the sidlo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sidlo }
         *     
         */
        public void setSidlo(Sidlo value) {
            this.sidlo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Vyska" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ZlozenieSposob" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ZlozenieCisloUctu" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ZlozenieAdresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ZlozenieDoklad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ZlozenieLehota" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Vratenie" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vyska",
        "zlozenieSposob",
        "zlozenieCisloUctu",
        "zlozenieAdresa",
        "zlozenieDoklad",
        "zlozenieLehota",
        "vratenie"
    })
    public static class Zabezpeka {

        @XmlElement(name = "Vyska", required = true)
        protected String vyska;
        @XmlElement(name = "ZlozenieSposob", required = true)
        protected String zlozenieSposob;
        @XmlElement(name = "ZlozenieCisloUctu", required = true)
        protected String zlozenieCisloUctu;
        @XmlElement(name = "ZlozenieAdresa", required = true)
        protected String zlozenieAdresa;
        @XmlElement(name = "ZlozenieDoklad", required = true)
        protected String zlozenieDoklad;
        @XmlElement(name = "ZlozenieLehota", required = true)
        protected String zlozenieLehota;
        @XmlElement(name = "Vratenie", required = true)
        protected String vratenie;

        /**
         * Gets the value of the vyska property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVyska() {
            return vyska;
        }

        /**
         * Sets the value of the vyska property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVyska(String value) {
            this.vyska = value;
        }

        /**
         * Gets the value of the zlozenieSposob property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZlozenieSposob() {
            return zlozenieSposob;
        }

        /**
         * Sets the value of the zlozenieSposob property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZlozenieSposob(String value) {
            this.zlozenieSposob = value;
        }

        /**
         * Gets the value of the zlozenieCisloUctu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZlozenieCisloUctu() {
            return zlozenieCisloUctu;
        }

        /**
         * Sets the value of the zlozenieCisloUctu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZlozenieCisloUctu(String value) {
            this.zlozenieCisloUctu = value;
        }

        /**
         * Gets the value of the zlozenieAdresa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZlozenieAdresa() {
            return zlozenieAdresa;
        }

        /**
         * Sets the value of the zlozenieAdresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZlozenieAdresa(String value) {
            this.zlozenieAdresa = value;
        }

        /**
         * Gets the value of the zlozenieDoklad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZlozenieDoklad() {
            return zlozenieDoklad;
        }

        /**
         * Sets the value of the zlozenieDoklad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZlozenieDoklad(String value) {
            this.zlozenieDoklad = value;
        }

        /**
         * Gets the value of the zlozenieLehota property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZlozenieLehota() {
            return zlozenieLehota;
        }

        /**
         * Sets the value of the zlozenieLehota property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZlozenieLehota(String value) {
            this.zlozenieLehota = value;
        }

        /**
         * Gets the value of the vratenie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVratenie() {
            return vratenie;
        }

        /**
         * Sets the value of the vratenie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVratenie(String value) {
            this.vratenie = value;
        }

    }

}
