//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 08:40:06 AM CEST 
//


package domain.v2.drazba;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZapisRegister complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZapisRegister">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JeObchodnyRegister" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="OrSud" type="{/PortalJustice/XmlFormularObchodnyVestnik/}XmlDropDownValue"/>
 *         &lt;element name="OrOddiel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrVlozka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InyRegistrovana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InyRegistracneCislo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZapisRegister", propOrder = {
    "jeObchodnyRegister",
    "orSud",
    "orOddiel",
    "orVlozka",
    "inyRegistrovana",
    "inyRegistracneCislo"
})
public class ZapisRegister {

    @XmlElement(name = "JeObchodnyRegister", namespace = "")
    protected boolean jeObchodnyRegister;
    @XmlElement(name = "OrSud", namespace = "", required = true)
    protected XmlDropDownValue orSud;
    @XmlElement(name = "OrOddiel", namespace = "", required = true)
    protected String orOddiel;
    @XmlElement(name = "OrVlozka", namespace = "", required = true)
    protected String orVlozka;
    @XmlElement(name = "InyRegistrovana", namespace = "", required = true)
    protected String inyRegistrovana;
    @XmlElement(name = "InyRegistracneCislo", namespace = "", required = true)
    protected String inyRegistracneCislo;

    /**
     * Gets the value of the jeObchodnyRegister property.
     * 
     */
    public boolean isJeObchodnyRegister() {
        return jeObchodnyRegister;
    }

    /**
     * Sets the value of the jeObchodnyRegister property.
     * 
     */
    public void setJeObchodnyRegister(boolean value) {
        this.jeObchodnyRegister = value;
    }

    /**
     * Gets the value of the orSud property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDropDownValue }
     *     
     */
    public XmlDropDownValue getOrSud() {
        return orSud;
    }

    /**
     * Sets the value of the orSud property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDropDownValue }
     *     
     */
    public void setOrSud(XmlDropDownValue value) {
        this.orSud = value;
    }

    /**
     * Gets the value of the orOddiel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrOddiel() {
        return orOddiel;
    }

    /**
     * Sets the value of the orOddiel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrOddiel(String value) {
        this.orOddiel = value;
    }

    /**
     * Gets the value of the orVlozka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrVlozka() {
        return orVlozka;
    }

    /**
     * Sets the value of the orVlozka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrVlozka(String value) {
        this.orVlozka = value;
    }

    /**
     * Gets the value of the inyRegistrovana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInyRegistrovana() {
        return inyRegistrovana;
    }

    /**
     * Sets the value of the inyRegistrovana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInyRegistrovana(String value) {
        this.inyRegistrovana = value;
    }

    /**
     * Gets the value of the inyRegistracneCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInyRegistracneCislo() {
        return inyRegistracneCislo;
    }

    /**
     * Sets the value of the inyRegistracneCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInyRegistracneCislo(String value) {
        this.inyRegistracneCislo = value;
    }

}
