//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 08:37:40 AM CEST 
//


package domain.v1.drazba;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anasoft.domain.v1.drazba package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DrazbaNotar_QNAME = new QName("/PortalJustice/XmlFormularObchodnyVestnik/", "Notar");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anasoft.domain.v1.drazba
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Drazba }
     * 
     */
    public Drazba createDrazba() {
        return new Drazba();
    }

    /**
     * Create an instance of {@link Drazba.Licitatori }
     * 
     */
    public Drazba.Licitatori createDrazbaLicitatori() {
        return new Drazba.Licitatori();
    }

    /**
     * Create an instance of {@link Drazba.Navrhovatelia }
     * 
     */
    public Drazba.Navrhovatelia createDrazbaNavrhovatelia() {
        return new Drazba.Navrhovatelia();
    }

    /**
     * Create an instance of {@link PravnickaOsoba }
     * 
     */
    public PravnickaOsoba createPravnickaOsoba() {
        return new PravnickaOsoba();
    }

    /**
     * Create an instance of {@link Drazba.Notar }
     * 
     */
    public Drazba.Notar createDrazbaNotar() {
        return new Drazba.Notar();
    }

    /**
     * Create an instance of {@link Drazba.Zabezpeka }
     * 
     */
    public Drazba.Zabezpeka createDrazbaZabezpeka() {
        return new Drazba.Zabezpeka();
    }

    /**
     * Create an instance of {@link XmlDropDownValue }
     * 
     */
    public XmlDropDownValue createXmlDropDownValue() {
        return new XmlDropDownValue();
    }

    /**
     * Create an instance of {@link Sidlo }
     * 
     */
    public Sidlo createSidlo() {
        return new Sidlo();
    }

    /**
     * Create an instance of {@link CeleMeno }
     * 
     */
    public CeleMeno createCeleMeno() {
        return new CeleMeno();
    }

    /**
     * Create an instance of {@link ZapisRegister }
     * 
     */
    public ZapisRegister createZapisRegister() {
        return new ZapisRegister();
    }

    /**
     * Create an instance of {@link ObchodneMenoSidlo }
     * 
     */
    public ObchodneMenoSidlo createObchodneMenoSidlo() {
        return new ObchodneMenoSidlo();
    }

    /**
     * Create an instance of {@link Drazba.Licitatori.Licitator }
     * 
     */
    public Drazba.Licitatori.Licitator createDrazbaLicitatoriLicitator() {
        return new Drazba.Licitatori.Licitator();
    }

    /**
     * Create an instance of {@link Drazba.Navrhovatelia.Navrhovatel }
     * 
     */
    public Drazba.Navrhovatelia.Navrhovatel createDrazbaNavrhovateliaNavrhovatel() {
        return new Drazba.Navrhovatelia.Navrhovatel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Drazba.Notar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "/PortalJustice/XmlFormularObchodnyVestnik/", name = "Notar", scope = Drazba.class)
    public JAXBElement<Drazba.Notar> createDrazbaNotar(Drazba.Notar value) {
        return new JAXBElement<Drazba.Notar>(_DrazbaNotar_QNAME, Drazba.Notar.class, Drazba.class, value);
    }

}
