//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 08:39:48 AM CEST 
//


package domain.v2.spravca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PravnickaOsoba complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PravnickaOsoba">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObchodneMenoNazov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sidlo" type="{/PortalJustice/XmlFormularObchodnyVestnik/}Sidlo"/>
 *         &lt;element name="Sud" type="{/PortalJustice/XmlFormularObchodnyVestnik/}XmlDropDownValue"/>
 *         &lt;element name="Oddiel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vlozka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PravnickaOsoba", propOrder = {
    "obchodneMenoNazov",
    "sidlo",
    "sud",
    "oddiel",
    "vlozka",
    "ico"
})
public class PravnickaOsoba {

    @XmlElement(name = "ObchodneMenoNazov", required = true)
    protected String obchodneMenoNazov;
    @XmlElement(name = "Sidlo", required = true)
    protected Sidlo sidlo;
    @XmlElement(name = "Sud", required = true)
    protected XmlDropDownValue sud;
    @XmlElement(name = "Oddiel", required = true)
    protected String oddiel;
    @XmlElement(name = "Vlozka", required = true)
    protected String vlozka;
    @XmlElement(name = "Ico", required = true)
    protected String ico;

    /**
     * Gets the value of the obchodneMenoNazov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObchodneMenoNazov() {
        return obchodneMenoNazov;
    }

    /**
     * Sets the value of the obchodneMenoNazov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObchodneMenoNazov(String value) {
        this.obchodneMenoNazov = value;
    }

    /**
     * Gets the value of the sidlo property.
     * 
     * @return
     *     possible object is
     *     {@link Sidlo }
     *     
     */
    public Sidlo getSidlo() {
        return sidlo;
    }

    /**
     * Sets the value of the sidlo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sidlo }
     *     
     */
    public void setSidlo(Sidlo value) {
        this.sidlo = value;
    }

    /**
     * Gets the value of the sud property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDropDownValue }
     *     
     */
    public XmlDropDownValue getSud() {
        return sud;
    }

    /**
     * Sets the value of the sud property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDropDownValue }
     *     
     */
    public void setSud(XmlDropDownValue value) {
        this.sud = value;
    }

    /**
     * Gets the value of the oddiel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOddiel() {
        return oddiel;
    }

    /**
     * Sets the value of the oddiel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOddiel(String value) {
        this.oddiel = value;
    }

    /**
     * Gets the value of the vlozka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVlozka() {
        return vlozka;
    }

    /**
     * Sets the value of the vlozka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVlozka(String value) {
        this.vlozka = value;
    }

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIco() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIco(String value) {
        this.ico = value;
    }

}
