//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 08:39:00 AM CEST 
//


package domain.v1.exekutor;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anasoft.domain.v1.exekutor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZoznamPodani_QNAME = new QName("", "zoznam_podani");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anasoft.domain.v1.exekutor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SudnyExekutor }
     * 
     */
    public SudnyExekutor createSudnyExekutor() {
        return new SudnyExekutor();
    }

    /**
     * Create an instance of {@link SudnyExekutor.PredmetDrazby }
     * 
     */
    public SudnyExekutor.PredmetDrazby createSudnyExekutorPredmetDrazby() {
        return new SudnyExekutor.PredmetDrazby();
    }

    /**
     * Create an instance of {@link SudnyExekutor.PredmetDrazby.Stavby }
     * 
     */
    public SudnyExekutor.PredmetDrazby.Stavby createSudnyExekutorPredmetDrazbyStavby() {
        return new SudnyExekutor.PredmetDrazby.Stavby();
    }

    /**
     * Create an instance of {@link SudnyExekutor.PredmetDrazby.Parcely }
     * 
     */
    public SudnyExekutor.PredmetDrazby.Parcely createSudnyExekutorPredmetDrazbyParcely() {
        return new SudnyExekutor.PredmetDrazby.Parcely();
    }

    /**
     * Create an instance of {@link SudnyExekutor.Hlavicka }
     * 
     */
    public SudnyExekutor.Hlavicka createSudnyExekutorHlavicka() {
        return new SudnyExekutor.Hlavicka();
    }

    /**
     * Create an instance of {@link SudniExekutori }
     * 
     */
    public SudniExekutori createSudniExekutori() {
        return new SudniExekutori();
    }

    /**
     * Create an instance of {@link SudnyExekutor.OpravaUdajov }
     * 
     */
    public SudnyExekutor.OpravaUdajov createSudnyExekutorOpravaUdajov() {
        return new SudnyExekutor.OpravaUdajov();
    }

    /**
     * Create an instance of {@link SudnyExekutor.PredmetDrazby.OznacenieNehnutelnosti }
     * 
     */
    public SudnyExekutor.PredmetDrazby.OznacenieNehnutelnosti createSudnyExekutorPredmetDrazbyOznacenieNehnutelnosti() {
        return new SudnyExekutor.PredmetDrazby.OznacenieNehnutelnosti();
    }

    /**
     * Create an instance of {@link SudnyExekutor.PredmetDrazby.Stavby.Stavba }
     * 
     */
    public SudnyExekutor.PredmetDrazby.Stavby.Stavba createSudnyExekutorPredmetDrazbyStavbyStavba() {
        return new SudnyExekutor.PredmetDrazby.Stavby.Stavba();
    }

    /**
     * Create an instance of {@link SudnyExekutor.PredmetDrazby.Parcely.Parcela }
     * 
     */
    public SudnyExekutor.PredmetDrazby.Parcely.Parcela createSudnyExekutorPredmetDrazbyParcelyParcela() {
        return new SudnyExekutor.PredmetDrazby.Parcely.Parcela();
    }

    /**
     * Create an instance of {@link SudnyExekutor.Hlavicka.Exekutor }
     * 
     */
    public SudnyExekutor.Hlavicka.Exekutor createSudnyExekutorHlavickaExekutor() {
        return new SudnyExekutor.Hlavicka.Exekutor();
    }

    /**
     * Create an instance of {@link SudnyExekutor.Hlavicka.ZastupujuciExekutor }
     * 
     */
    public SudnyExekutor.Hlavicka.ZastupujuciExekutor createSudnyExekutorHlavickaZastupujuciExekutor() {
        return new SudnyExekutor.Hlavicka.ZastupujuciExekutor();
    }

    /**
     * Create an instance of {@link SudnyExekutor.Hlavicka.DrazbaMiesto }
     * 
     */
    public SudnyExekutor.Hlavicka.DrazbaMiesto createSudnyExekutorHlavickaDrazbaMiesto() {
        return new SudnyExekutor.Hlavicka.DrazbaMiesto();
    }

    /**
     * Create an instance of {@link SudnyExekutor.Hlavicka.Vlastnik }
     * 
     */
    public SudnyExekutor.Hlavicka.Vlastnik createSudnyExekutorHlavickaVlastnik() {
        return new SudnyExekutor.Hlavicka.Vlastnik();
    }

    /**
     * Create an instance of {@link SudnyExekutor.Hlavicka.Ohliadka }
     * 
     */
    public SudnyExekutor.Hlavicka.Ohliadka createSudnyExekutorHlavickaOhliadka() {
        return new SudnyExekutor.Hlavicka.Ohliadka();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SudniExekutori }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zoznam_podani")
    public JAXBElement<SudniExekutori> createZoznamPodani(SudniExekutori value) {
        return new JAXBElement<SudniExekutori>(_ZoznamPodani_QNAME, SudniExekutori.class, null, value);
    }

}
